//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestingProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using OpenQA.Selenium;
        ///using OpenQA.Selenium.Chrome;
        ///using OpenQA.Selenium.Interactions;
        ///
        ///namespace seleniumTest
        ///{
        ///    public class Chrome
        ///    {
        ///        private static IWebDriver _driver;
        ///
        ///        public static IWebDriver Driver() //singleton method - this is terrible for multiple-browser tests
        ///        {
        ///            if (_driver == null)
        ///            {
        ///
        ///                //var service = ChromeDriverService.CreateDefaultService(); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string browserStarts {
            get {
                return ResourceManager.GetString("browserStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using OpenQA.Selenium;
        ///using OpenQA.Selenium.Chrome;
        ///using OpenQA.Selenium.Interactions;
        ///
        ///namespace seleniumTest //my next step is to change most of these to have correct private/public consolidation. 
        ///{
        ///    public class generalHandlers
        ///    { 
        ///
        ///        public generalHandlers() { } //constructor
        ///
        ///        public void browserStart(string temp) //also navigates to page
        ///        {
        ///            Chrome.Driver().Navigate().GoToUrl(temp); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string generalHandlers {
            get {
                return ResourceManager.GetString("generalHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using OpenQA.Selenium;
        ///using OpenQA.Selenium.Chrome;
        ///using OpenQA.Selenium.Interactions;
        ///
        ///namespace seleniumTest
        ///{
        ///    public class loadCreator
        ///    {
        ///
        ///        generalHandlers constructor = new generalHandlers();
        ///        locationDefinitions definitions = new locationDefinitions();
        ///
        ///        public loadCreator() { }
        ///
        ///        public void changethisname() //this entire section needs to get moved into functions
        ///        {
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string loadCreator {
            get {
                return ResourceManager.GetString("loadCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace seleniumTest
        ///{
        ///		public class locationDefinitions
        ///		{
        ///			Random rand = new Random();
        ///			public string[] randomizedItems;
        ///
        ///			public locationDefinitions() //constructor
        ///			{
        ///				string[] randomizedItems = {
        ///				names[rand.Next(names.Length)],
        ///				address1[rand.Next(address1.Length)],
        ///				address2[rand.Next(address2.Length)],
        ///				city_Blocks[rand.Next(5),rand.Next(2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locationDefinitions {
            get {
                return ResourceManager.GetString("locationDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
