//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestingProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using OpenQA.Selenium;
        ///using OpenQA.Selenium.Chrome;
        ///using OpenQA.Selenium.Interactions;
        ///
        ///namespace Selenium
        ///{
        ///    public class BannerButtons
        ///    {
        ///        public BannerButtons()
        ///        {
        ///            IBrowsers driver = new Driver();
        ///            Navigate QC = new Navigate(driver);
        ///            QC.Nav(Constants.URLs[0]);
        ///            new LoginPage(driver);
        ///
        ///            var banner = new Banner(driver);
        ///            for (int g = 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BannerButtons {
            get {
                return ResourceManager.GetString("BannerButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using OpenQA.Selenium;
        ///using OpenQA.Selenium.Support.UI;
        ///using OpenQA.Selenium.Interactions;
        ///using System;
        ///
        ///namespace Selenium //my next step is to change most of these to have correct private/public consolidation. 
        ///{
        ///    public class BaseComponent
        ///    {
        ///        private protected IBrowsers driver { get; set; }
        ///        private protected By locator { get; set; } //-look up how this works, future me! ~~~ Future me says that this is the start of a property that you&apos;re not using. 
        ///
        ///        public IBr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseComponent {
            get {
                return ResourceManager.GetString("BaseComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using OpenQA.Selenium;
        ///
        ///namespace Selenium
        ///{
        ///    public class Button : BaseComponent
        ///    {
        ///        public Button(IBrowsers driver, By locator) : base(driver, locator) {  }
        ///
        ///        public void Click()
        ///        {
        ///            FindElement().Click();
        ///        }
        ///
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Selenium
        ///{
        ///    public class Constants
        ///    {
        ///        public static string[] Names =
        ///        {
        ///            &quot;John Denver&quot;,
        ///            &quot;Lottery Winner&quot;,
        ///            &quot;Jessie Dean&quot;,
        ///            &quot;Aisha Mathews&quot;,
        ///            &quot;Traci Sawyer&quot;,
        ///            &quot;Taran Chandler&quot;,
        ///            &quot;Clarence Henderson&quot;,
        ///            &quot;Zahra Curry&quot;,
        ///            &quot;Millie-Rose Pruitt&quot;
        ///        };
        ///
        ///        public static string[] Address1 =
        ///        {
        ///            &quot;123 America Street&quot;,
        ///            &quot;9576 West W E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Constants {
            get {
                return ResourceManager.GetString("Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using OpenQA.Selenium;
        ///using OpenQA.Selenium.Chrome;
        ///
        ///namespace Selenium
        ///{
        ///    public interface IBrowsers
        ///    {
        ///        IWebDriver CurrentDriver();
        ///        //By Locator();
        ///        //object Navigate();
        ///        //IWebDriver ChromeDriver();
        ///        //Edge();
        ///        //Firefox();
        ///
        ///    }
        ///    class Driver : IBrowsers
        ///    {
        ///        private IWebDriver _driver;
        ///        public Driver()
        ///        {
        ///            _driver = new ChromeDriver();            //variable names will need to be changed for clari [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DriverLogic {
            get {
                return ResourceManager.GetString("DriverLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using OpenQA.Selenium;
        ///using OpenQA.Selenium.Interactions;
        ///
        ///namespace Selenium
        ///{
        ///    public class Dropdowns : BaseComponent
        ///    {
        ///        public Dropdowns(IBrowsers driver, By locator) : base(driver, locator) 
        ///        {
        ///            //kinda just doubled up buttons; just using buttons twice on a page module does the same thing
        ///
        ///        }
        ///
        ///        public void Type2() //Click
        ///        {
        ///
        ///        }
        ///
        ///        public void Type3() //
        ///        {
        ///
        ///        }
        ///
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Dropdowns {
            get {
                return ResourceManager.GetString("Dropdowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using OpenQA.Selenium;
        ///using OpenQA.Selenium.Support.UI;
        ///using OpenQA.Selenium.Interactions;
        ///using System;
        ///
        ///namespace Selenium
        ///{
        ///    public class Hover : BaseComponent
        ///    {
        ///        public Hover(IBrowsers driver, By locator) : base(driver, locator)
        ///        {
        ///            Actions action = new Actions(base.driver.CurrentDriver());
        ///            action.MoveToElement(FindElement()).Perform();
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Hover {
            get {
                return ResourceManager.GetString("Hover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using OpenQA.Selenium;
        ///using OpenQA.Selenium.Chrome;
        ///using OpenQA.Selenium.Interactions;
        ///
        ///namespace Selenium
        ///{
        ///    internal class LoadCreator
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string LoadCreator {
            get {
                return ResourceManager.GetString("LoadCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using OpenQA.Selenium;
        ///using OpenQA.Selenium.Chrome;
        ///using OpenQA.Selenium.Interactions;
        ///
        ///namespace Selenium
        ///{
        ///    public class Navigate : BaseComponent
        ///    {
        ///        public Navigate(IBrowsers driver) : base(driver) { }
        ///        public void Nav(string URL) 
        ///        {
        ///            driver.CurrentDriver().Navigate().GoToUrl(URL);
        ///        }
        ///
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Navigate {
            get {
                return ResourceManager.GetString("Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using OpenQA.Selenium;
        ///using OpenQA.Selenium.Chrome;
        ///using OpenQA.Selenium.Interactions;
        ///using System.Collections.Generic;
        ///using Microsoft.Office.Interop.Excel;
        ///
        ///namespace Selenium
        ///{
        ///    public class ButtonList
        ///    {
        ///        private List&lt;Button&gt; _currentButtonList { get; set; }
        ///        public List&lt;Button&gt; CurrentButtonList
        ///        {
        ///            get { return _currentButtonList; }
        ///            set { _currentButtonList = value; }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectLists {
            get {
                return ResourceManager.GetString("ObjectLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///
        ///namespace Selenium
        ///{
        ///    public class RandomLocation
        ///    {
        ///        Random rand = new Random();
        ///        //public string[] RandomList = new string[5]; 
        ///        public List&lt;string&gt; RandomList = new List&lt;string&gt;();
        ///
        ///        public RandomLocation() //constructor, but a more classic usage
        ///        {
        ///            RandomList[0] = Constants.Names[rand.Next(0, Constants.Names.Length)];
        ///            RandomList[1] = Constants.Address1[rand.Next(0, Constants.Ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RandomLocation {
            get {
                return ResourceManager.GetString("RandomLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using OpenQA.Selenium;
        ///namespace Selenium
        ///{
        ///    public class Textbox : BaseComponent
        ///    {
        ///        public Textbox(IBrowsers driver, By locator) : base(driver, locator) { }
        ///
        ///        public void SendKeys(string text)
        ///        {
        ///            FindElement().SendKeys(text);
        ///        }
        ///
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Textbox {
            get {
                return ResourceManager.GetString("Textbox", resourceCulture);
            }
        }
    }
}
